version: '2.0.{build}'
image: Visual Studio 2017
before_build:
  - nuget restore Parse.sln
build_script:
  project: Parse.sln
  verbosity: minimal
before_test:  
  - choco install opencover.portable
test_script:
  - OpenCover.Console.exe -target:dotnet.exe -targetargs:"test /p:DebugType=full .\Parse.Test\Parse.Test.csproj" -filter:"+[Parse*]* -[Parse.Test*]*" -oldstyle -output:parse_sdk_dotnet_coverage.xml -register:user
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "parse_sdk_dotnet_coverage.xml"